### ISSUE TITLE
Issue trying to install Nsound Module

### ISSUE THREAD

**Issue by jayhill90** [weegreenblobbie/nsound#11]
I'm trying to install the Nsound module and keep getting an error staging "Could not find tool scons is it installed? Is it in your PATH?" 

```
Collecting nsound
  Using cached Nsound-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Checking for scons ...Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y9/w2qsjqrj0pl4z03gk3pjd72m0000gp/T/pip-build-ljmLmM/nsound/setup.py", line 196, in <module>
        if __name__ == "__main__": main()
      File "/private/var/folders/y9/w2qsjqrj0pl4z03gk3pjd72m0000gp/T/pip-build-ljmLmM/nsound/setup.py", line 33, in main
        tool_check()
      File "/private/var/folders/y9/w2qsjqrj0pl4z03gk3pjd72m0000gp/T/pip-build-ljmLmM/nsound/setup.py", line 93, in tool_check
        " is it installed?  Is it in your PATH?" % t)
    RuntimeError: FAILURE!
    Could not find tool 'scons', is it installed?  Is it in your PATH?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y9/w2qsjqrj0pl4z03gk3pjd72m0000gp/T/pip-build-ljmLmM/nsound/
```

Scons is installed and is running 2.5.1. This is for python 2.7. Anyone have an idea on how to get this to install the module properly? Thanks! This is on Mac OSX Sierra.

**Comment by weegreenblobbie** [comment]
Is it possible that your default python is 3.x?  How are you installing
nsound?

**Comment by jayhill90** [comment]
I'm running 2.7.13.

```
python --version
Python 2.7.13
```

I'm using pip install --user nsound and have tried different variations of it as well.

Thanks Nick!

**Comment by weegreenblobbie** [comment]
I don't know why it's not working for you without debugging it myself.  You can try this, clone it from github and run these commands yourself:

```bash
scons setup_builder.py
python setup.py install --user
```

With these commands, you can be explicit which scons you are using and python interpreter.

**Comment by jayhill90** [comment]
Cool thanks Nick. I'll give it a shot.

**Comment by jayhill90** [comment]
After installing xcode, using xcode-select -switch, and a few other commands I think I've got it working. Thanks for the help Nick!
