### ISSUE TITLE
Nsound (or a dependency) tries to use PyInstance_Type on Python 3

### ISSUE THREAD

**Issue by Poikilos** [weegreenblobbie/nsound#19]
```
>>> import Nsound as ns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/owner/.local/lib/python3.7/site-packages/Nsound.py", line 15, in <module>
    import _Nsound
ImportError: /home/owner/.local/lib/python3.7/site-packages/_Nsound.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyInstance_Type
```

- A way to make it compatible with both is here: <https://python.readthedocs.io/en/latest/howto/cporting.html?highlight=py_initmodule>
- I can't tell why it is using `PyInstance_Type` in Python 3, and why the error only appears on import (and not during pip install as would usually be the case). 

- OS: Debian 10 

(Nsound imports successfully on Python 2 on the same system and the bebot-disp.py example runs)

**Comment by weegreenblobbie** [comment]
I've just published 0.9.5.0 to pypi: https://pypi.org/project/Nsound/0.9.5/.  Please reopen or report a new issue if you encounter problems.
