### ISSUE TITLE
How to install system wide ? 

### ISSUE THREAD

**Issue by journeytosilius** [weegreenblobbie/nsound#24]
I have followed the install instructions to build on C++ and after building it, I include the headers and link the .so library on my CmakeLists but the includes on  the examples I believe expect the library to be installed on the system ? 

`#include <Nsound/NsoundAll.h>`

```
 fatal error: 'Nsound/NsoundAll.h' file not found
#include <Nsound/NsoundAll.h>
```

Is there a step I'm missing or something ?  Thanks !

**Comment by weegreenblobbie** [comment]
Try adding the src dir to the include path so the compiler can find it.

**Comment by journeytosilius** [comment]
Thanks it's working now :)
