### ISSUE TITLE
how to play some instruments together?

### ISSUE THREAD

**Issue by summer995** [weegreenblobbie/nsound#7]
Hi, I am currently using nsound and it is much easier than csound. But I dont know how I can play some different kinds of instruments together, can you help me with that? Thank you so much!

**Comment by weegreenblobbie** [comment]
The `AudioStream` class has [add()](https://github.com/weegreenblobbie/nsound/blob/master/src/Nsound/AudioStream.h#L84) function where you can specify an offset in seconds.

The `Buffer` class also has an [add()](https://github.com/weegreenblobbie/nsound/blob/master/src/Nsound/Buffer.h#L177) function where you can specify an offset in samples.

With these two methods, you can add instruments together with the desired offset to an output `AudioStream` or `Buffer`.

Checkout the `OrganPipe::play()` [demo](https://github.com/weegreenblobbie/nsound/blob/v0.9.4/src/Nsound/OrganPipe.cc#L55), it uses the `AudioStream::add()` to get overlapping notes playing.  Here's a link to the demo [audio](http://nsound.sourceforge.net/users_guide/_downloads/OrganPipe.mp3) that it plays.

Does this answer your question?

**Comment by summer995** [comment]
Thank you very much! 
I have learned how to play different kinds of mucic at the same time with the funtion add(). It is really easy to make some music in Nsound compared with Csound (that is so hard!). I am currently doing a project of accompanying music with different kind of instrument. So I'm tring to find the tools to do that, and Nsound is great! One suggestion, if you can create more playing pattern in different instrument, like different patterns of drum beating, it would be much easier for people to create music in Nsound. It is a little bit hard for people who like making music but don't know how to make the playing patterns, just like me, hahaha.
 Nsound is a really tool. It has save me a lot time to learn csound. Thank you again!
